language: cpp
sudo: false
git:
  depth: 3
dist: bionic
matrix:
  include:
  - os: linux
    compiler: gcc
    script:
    - make sdl2
    - make glfw
  - os: windows
    language: cpp
    install:
    - choco install nsis 7zip
    script:
    - cmake . -BBuild -DTB_RENDERER=GL3 -DTB_BUILD_DEMO=GLFW -DTB_BUILD_GLFW=ON #-DCMAKE_VERBOSE_MAKEFILE:BOOL=ON
#    - cmake . -BBuild -DTB_RENDERER=GL3 -DTB_BUILD_DEMO=SDL2 -DTB_BUILD_SDL2=ON #-DCMAKE_VERBOSE_MAKEFILE:BOOL=ON
    - ls
    - ls Build
    - cmake --build Build --config Release --target PACKAGE
  - os: osx
    osx_image: xcode9.1
    script:
    - echo ${CXX}
    - make sdl2
    - make glfw
    - make osx
#    - make ios # needs code signing setup
#  - language: android
#    os: linux
#    dist: trusty
#    env:
#    - TARGET=android
#    android:
#      components:
#      - build-tools-26.0.2
#      - android-26
#    script:
#    - cd $HOME
#    - wget https://dl.google.com/android/repository/android-ndk-r16b-linux-x86_64.zip &&
#    - unzip -q android-*.zip && cd $TRAVIS_BUILD_DIR 
#    - |
#      cmake .. \
#      -DCMAKE_ANDROID_NDK=$HOME/android-ndk-r16b \
#      -DCMAKE_SYSTEM_NAME=Android \
#      -DCMAKE_SYSTEM_VERSION=22

addons:
  apt:
    packages:
    - cmake
    - clang
    - rpm
    - libgl1-mesa-dev
    - libx11-dev
    - libxrandr-dev
    - libwayland-dev
    - libxinerama-dev
    - libxxf86vm-dev
    - libxcursor-dev
    - libxi-dev
before_install:
- ${CXX} --version
- cmake --version
script: 
after_failure:
- pwd
- find .
- cat Build/CMakeFiles/CMakeOutput.log
- ls thirdparty
- cat thirdparty/CMakeFiles/CMakeOutput.log
deploy:
  provider: releases
  api_key:
    secure: IbObTxgvPEMtr4kfjVTa+SPSXuTLPPoxoJiy5mvrZVsXisTqnW+3se6NIsGXuW07dYO1RS3jRUGmYweyPzWBIAvlDXGajLOQr1n/rXSZcJif9iV9P0srIJni7CdNnTRLI2Lse8hTqUjRxTAfDZ40npj4+6BCTZuxUvt2OOjIdu5gdxMPSpZ/lAE2O/M5H0TNqvmPSQ2QmbT5pZLOnwAO7CG4MX0xEOpINQTzTfbu040FB+yqNegI1Zp/rDQ5GdyEQ5KsLl0sfHyxTlr2BbE3JLzrdH+9fM2AeotqxVenO/R9eoxUG5vI8UcoOWvVz6C5LbEkgKEay6BFTzfQ/bWimg0V7mjng8qBxFWVR0a7CMv46PGh8HdUjkUgkF49biB0xh67I6BqsFzBabDRhy2LNnw5ciVgV5jH/+cbrTBddFt5cBgK83H1o+tzcED1ac9es8jQqSSot0h6CwArOZHEqtIdzTdewbi1ggo4yUBf8tEKYQKRIcK95J42TFjpusn/4Q5dsggHgTCkcF2uYjdTTn/SO2m2QrM/Wy+kzf050wPg0LBZ0mVRHQEtB0TgFvluBDOw3bENXOqQLQgokB3GQXh2nQg/jull+3mlAy1o+bahBTjXMAOcT9aSlZg0B0zqwztpPySMmEy2bQvunACl7YzX8KYewjN0nn5pkoGIFdA=
  file_glob: true
  file:
    - Build*/TurboBadgerDemo*install-win32.exe
    - Build*/TurboBadgerDemo*install-win32.zip
    - Build*/TurboBadgerDemo*.dmg
    - Build*/TurboBadgerDemo*.deb
    - Build*/TurboBadgerDemo*.rpm
    - Build*/TurboBadgerDemo*.tar.gz
  skip_cleanup: true
  overwrite: true
  draft: true
  on:
    repo: tesch1/turbobadger
    tags: true
#    branch: hastybadger
