version: 2.1

commands:
  get_build_test:
    description: "Checkout, Build, and Test"
    parameters:
      platform:
        type: string
        default: "GenericPlatform"
    steps:
      - checkout # check out source code to working directory
      - run:
          name: Install System Dependencies
          command: |
            #lsb_release -a
            [ -f /etc/debian_version ] && cat /etc/debian_version
            #apt-get install -y cmake
            echo $SHELL
            command -v sudo >/dev/null 2>&1 && SUDO=sudo
            $SUDO apt-get update
            $SUDO apt-get install -y gcc g++ cmake xorg-dev libglu1-mesa-dev
            gcc --version
            g++ --version
      - run:
          name: Build TurboBadger SDL2
          command: make sdl2
      - run:
          name: Build TurboBadger GLFW
          command: make glfw
      - run:
          name: Build TurboBadger Android
          command: |
            echo "ANDROID_NDK_HOME: $ANDROID_NDK_HOME"
            cd DemoAndroid2 && ./gradlew build
      - run:
          name: Build Failed
          when: on_fail
          command: |
            echo build fail
      - run:
          name: Test TurboBadger
          command: |
            echo run tests
      - run:
          name: Tests Failed
          when: on_fail
          command: |
            echo failed
      - store_artifacts:
          name: Store Results
          path: app/build/reports
          destination: reports

jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point
    working_directory: ~/turbobadger # directory where steps will run

    docker: # run the steps with Docker
#      - image: buildpack-deps:xenial
      - image: ubuntu:18.04
#      - image: circleci/android:api-24-ndk
#      - image: trzeci/emscripten
#      - image: trzeci/emscripten-slim

    steps: # a collection of executable commands
      - get_build_test
